name: 'Build'

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Caching Assets
      id: blog-cache-assets
      uses: actions/cache@v3
      with:
        path: |
          resources/_gen
          .cache
        key: ${{ runner.os }}-blog-assets-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-blog-assets-
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install ffmpeg -y
    - name: 'Check Ffmpeg'
      run: ffmpeg -version
    - name: Check ImageMagick
      run: convert -version
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.3'
    - name: 'Import posts and assets'
      run: |
        npx craft-content --dist content/posts
    - name: Build
      run: hugo --minify
    - name: Configure SSH
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa.key
        chmod 600 ~/.ssh/id_rsa.key
        cat >>~/.ssh/config <<END
        Host blog
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/id_rsa.key
          StrictHostKeyChecking no
        END
    - name: Deploy
      run: |
        rsync -avz --delete ./public/ blog:/root/platform/data/blog
    - name: 'Notify: deployded'
      run: |
        curl -X POST -H 'Content-type: application/json' \
        -H "Authorization: Bearer ${{ secrets.NOTIFIER_ACCESS_TOKEN }}" \
        --data '{"message":"⬆️ *Husky-blog*: deployed"}' \
        https://notifier.husky-dev.me/notify
